github: [metadata]
kramdown:
 input: GFM
 hard_wrap: false
permalink: /:title
gems:
   - jekyll-coffeescript
   - jekyll-paginate
   - jekyll-redirect-from
#   - jemoji

baseurl: ""
url: "https://sunderb.me"
#url: http://127.0.0.1:4000 # for local testing
